### ISSUE TITLE
Architect should treat as templates all files in templates folder

### ISSUE THREAD

**Issue by r7vme** [giantswarm/architect#135]
It does this only for `deployment.yaml`.

**Comment by r7vme** [comment]
cc @JosephSalisbury

**Comment by marians** [comment]
Ran into this several times. With `cronjob.yaml` and `some-deployment.yaml`.

**Comment by JosephSalisbury** [comment]
Assuming accidental close, this isn't fixed yet.

**Comment by calvix** [comment]
is it fixed now? @JosephSalisbury

**Comment by JosephSalisbury** [comment]
I don't think so.

**Comment by calvix** [comment]
Seems like it might be fixed, as now I have `etcd-backup` and i switched back to `[[ .SHA ]]` and it worked even in `cronjob.yaml`

**Comment by calvix** [comment]
https://github.com/giantswarm/etcd-backup/pull/22/files#diff-e2bec8d30677f7b1d2d733db92561253

**Comment by JosephSalisbury** [comment]
That's good enough for me. If we hit this again, we can deal with it then.
