### ISSUE TITLE
Support yaml linting

### ISSUE THREAD

**Issue by indyfree** [giantswarm/architect#202]
Towards giantswarm/giantswarm#2706

We want architect to be able to lint yamls (of charts) as an optional step.

As a developer of a helm chart i want to add a step
```bash
./architect chart-lint
```
to my `.cirlceci/config.yaml` to be sure that my build fails when the templates are not in the correct format.

Kubernetes version of chart linting can be found [here](https://github.com/kubernetes/charts/tree/master/test/circle).

**Comment by indyfree** [comment]
Discussions in SIG Sync resulted in some insights, if it wouldn't be better to integrate the linting as a task of the helm workflow. That would better align with the general structure of architect and remove the need to update every single circle config to use linting. Downside is that all charts would need to be compatible/linted beforehand to not break the builds.

**Comment by MarcelMue** [comment]
Just to pick this issue up again a little bit: 
Could `architect` just execute `helm lint` in this step? It should be pretty straight forward then

**Comment by MarcelMue** [comment]
After I turned my brain on again, I realized that architect doesn't necessarily have the helm CLI on the same machine. So uncertain. I couldn't find the lint functionality in the helm client lib right away.
