### ISSUE TITLE
Bump Go version to 1.19

### ISSUE THREAD

**Issue by William-Young-97** [giantswarm/architect#774]
To run applications using 1.19 we need to update the architect container image. Specifically this is for [This PR](https://github.com/giantswarm/harbor-config-operator/pull/11)

**Comment by William-Young-97** [comment]
@MarcelMue Could I have access to this repository to push up the Go version bump?

**Comment by MarcelMue** [comment]
> @MarcelMue Could I have access to this repository to push up the Go version bump?

I would prefer to do this internally, this requires GS permissions to roll out AFAIK. Will get back to you in standup.

**Comment by William-Young-97** [comment]
Ok sweet

**Comment by William-Young-97** [comment]
Yeah I saw this very odd. On the circle CI it says it is failing because the go version used is linux amd 1.18 so it can't go mod tidy to 1.19. See [here](https://app.circleci.com/pipelines/github/giantswarm/harbor-config-operator/51/workflows/3493a3b4-c136-493a-8a4a-3a36ba05a045/jobs/59).
