### ISSUE TITLE
Update kubectl version

### ISSUE THREAD

**Issue by asymmetric** [giantswarm/architect#89]
The Docker image for `kubectl` is for version 1.4.7:

```
❯ docker run -it quay.io/giantswarm/docker-kubectl:1afa480ffb2912fe3605e84fd392c5bd1c9f48b9 version
Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2016-12-10T04:49:33Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

We should update to match the version running on the cluster.

Towards https://github.com/giantswarm/k8scloudconfig/issues/136

**Comment by JosephSalisbury** [comment]
This should be in https://github.com/giantswarm/docker-kubectl, no?

**Comment by asymmetric** [comment]
Yes, it should be there but we need to update the hard-coded version here too. So in both places? :)

**Comment by JosephSalisbury** [comment]
I forgot about https://github.com/giantswarm/architect/blob/master/configuration/guest/kubectl/kubectl.go#L11 <3
